server:
  port: 12000
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zhj@2010[]
    url: jdbc:mysql://192.168.226.128:3306/wms

  devtools:
    livereload:
      port: 12001

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    inetutils:
      ignored-interfaces: 'Hyper-V Virtual Ethernet Adapter,Hyper-V Virtual Ethernet Adapter #3,Hyper-V Virtual Ethernet Adapter #4,Hyper-V Virtual Ethernet Adapter #5,Hyper-V Virtual Ethernet Adapter #2,VMware Virtual Ethernet Adapter for VMnet1,VMware Virtual Ethernet Adapter for VMnet8'

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      table-prefix: wms_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
