server:
  port: 11000
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zhj@2010[]
    url: jdbc:mysql://192.168.226.128:3306/wms
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      table-prefix: wms_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
