server:
  port: 8000
  servlet:
    context-path: /

spring:
  application:
    name: member

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zhj@2010[]
    url: jdbc:mysql://192.168.244.128:3306/mms

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

  global-config:
    db-config:
      id-type: auto
      table-prefix: mms_

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl